# Generated by Django 2.0.7 on 2019-01-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='薪资'),
        ),
    ]
